# Add a label for release-drafter to ignore this commit as it is probably just being used to get master/develop up to speed with the other
ignore-develop-sync:
  head: "master"
  base: "develop"
# Add a label for release-drafter to ignore this commit as it is probably just being used to get master/develop up to speed with the other
ignore-master-sync:
  head: "develop"
  base: "master"
