namespace JavaInterop
{
    public enum JavaRequest
    {
        CLOSE_SESSION = 0,
        SCAN = 1,
        RESERVED = 2,
        LIST_APS_DETAIL = 3,
        CONNECT_TO_AP = 4,
        DISCONNECT = 5
    }

    public enum ResponseToJava
    {
        SESSION_CLOSED = 0,
        SESSION_OPENED = 1,
        NO_ADAPTERS_FOUND = 2,
        NO_WIFI_NETWORKS_FOUND = 3,
        SCAN_COMPLETED = 4,
        SCAN_FAILED = 5,
        CONNECTION_CONFIG_AWAITING_SSID = 6,
        CONNECTION_CONFIG_AWAITING_USERNAME = 7,
        CONNECTION_CONFIG_AWAITING_PASSWORD = 8,
        CONNECTION_CONFIG_AWAITING_DOMAIN = 9,
        CONNECTION_CONFIG_COMPLETED = 10,
        CONNECTION_COMPLETED = 11,
        CONNECTION_FAILED = 12,
        DISCONNECT_COMPLETED = 13,
        DISCONNECT_FAILED = 14,
        WARN_RECEIVED_GARBAGE_INPUT = 15,
        WARN_RECEIVED_INCORRECT_COMMAND = 16
    }
}